### ISSUE TITLE
How to remove the noisy across-and-down stripe

### ISSUE THREAD

**Issue by nkwangyh** [oxfordrobotics/robotcar-dataset-sdk#11]
I know that "LoadImage" can do this for both perspective and fisheye images. But after that the fisheye image is rectified. Since what I want is the raw fisheye image, how to get a raw fisheye image with the noisy stripes removed?

**Comment by nkwangyh** [comment]
I just find a 2-by-2 gaussian kernel with sigma as 0.5 works well. Or a simple 2-by-2 average filter is also ok.

**Comment by podgib** [comment]
It sounds like the stripes you're describing are the bayer pattern in the images. The images are all encoded as a single channel with a Bayer mosaic. If you look in the coad for LoadImage, you'll see a `demosaic` step before the rectification - if you apply this same demosaic step, but without the rectification, you will get a colour fisheye image.

**Comment by nkwangyh** [comment]
Thank you for your remind :+1:  I didn't notice that. Thank you very much.
